package com.hics.g500.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hics.g500.db.User;
import com.hics.g500.db.Gasolineras;

import com.hics.g500.db.UserDao;
import com.hics.g500.db.GasolinerasDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig gasolinerasDaoConfig;

    private final UserDao userDao;
    private final GasolinerasDao gasolinerasDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        gasolinerasDaoConfig = daoConfigMap.get(GasolinerasDao.class).clone();
        gasolinerasDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        gasolinerasDao = new GasolinerasDao(gasolinerasDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Gasolineras.class, gasolinerasDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        gasolinerasDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public GasolinerasDao getGasolinerasDao() {
        return gasolinerasDao;
    }

}
