package com.hics.g500.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hics.g500.db.User;
import com.hics.g500.db.Gasolineras;
import com.hics.g500.db.Encuesta;
import com.hics.g500.db.Preguntas;
import com.hics.g500.db.Opciones;
import com.hics.g500.db.Respuesta;
import com.hics.g500.db.RespuestaDetalle;

import com.hics.g500.db.UserDao;
import com.hics.g500.db.GasolinerasDao;
import com.hics.g500.db.EncuestaDao;
import com.hics.g500.db.PreguntasDao;
import com.hics.g500.db.OpcionesDao;
import com.hics.g500.db.RespuestaDao;
import com.hics.g500.db.RespuestaDetalleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig gasolinerasDaoConfig;
    private final DaoConfig encuestaDaoConfig;
    private final DaoConfig preguntasDaoConfig;
    private final DaoConfig opcionesDaoConfig;
    private final DaoConfig respuestaDaoConfig;
    private final DaoConfig respuestaDetalleDaoConfig;

    private final UserDao userDao;
    private final GasolinerasDao gasolinerasDao;
    private final EncuestaDao encuestaDao;
    private final PreguntasDao preguntasDao;
    private final OpcionesDao opcionesDao;
    private final RespuestaDao respuestaDao;
    private final RespuestaDetalleDao respuestaDetalleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        gasolinerasDaoConfig = daoConfigMap.get(GasolinerasDao.class).clone();
        gasolinerasDaoConfig.initIdentityScope(type);

        encuestaDaoConfig = daoConfigMap.get(EncuestaDao.class).clone();
        encuestaDaoConfig.initIdentityScope(type);

        preguntasDaoConfig = daoConfigMap.get(PreguntasDao.class).clone();
        preguntasDaoConfig.initIdentityScope(type);

        opcionesDaoConfig = daoConfigMap.get(OpcionesDao.class).clone();
        opcionesDaoConfig.initIdentityScope(type);

        respuestaDaoConfig = daoConfigMap.get(RespuestaDao.class).clone();
        respuestaDaoConfig.initIdentityScope(type);

        respuestaDetalleDaoConfig = daoConfigMap.get(RespuestaDetalleDao.class).clone();
        respuestaDetalleDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        gasolinerasDao = new GasolinerasDao(gasolinerasDaoConfig, this);
        encuestaDao = new EncuestaDao(encuestaDaoConfig, this);
        preguntasDao = new PreguntasDao(preguntasDaoConfig, this);
        opcionesDao = new OpcionesDao(opcionesDaoConfig, this);
        respuestaDao = new RespuestaDao(respuestaDaoConfig, this);
        respuestaDetalleDao = new RespuestaDetalleDao(respuestaDetalleDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Gasolineras.class, gasolinerasDao);
        registerDao(Encuesta.class, encuestaDao);
        registerDao(Preguntas.class, preguntasDao);
        registerDao(Opciones.class, opcionesDao);
        registerDao(Respuesta.class, respuestaDao);
        registerDao(RespuestaDetalle.class, respuestaDetalleDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        gasolinerasDaoConfig.clearIdentityScope();
        encuestaDaoConfig.clearIdentityScope();
        preguntasDaoConfig.clearIdentityScope();
        opcionesDaoConfig.clearIdentityScope();
        respuestaDaoConfig.clearIdentityScope();
        respuestaDetalleDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public GasolinerasDao getGasolinerasDao() {
        return gasolinerasDao;
    }

    public EncuestaDao getEncuestaDao() {
        return encuestaDao;
    }

    public PreguntasDao getPreguntasDao() {
        return preguntasDao;
    }

    public OpcionesDao getOpcionesDao() {
        return opcionesDao;
    }

    public RespuestaDao getRespuestaDao() {
        return respuestaDao;
    }

    public RespuestaDetalleDao getRespuestaDetalleDao() {
        return respuestaDetalleDao;
    }

}
