package com.hics.g500.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "GASOLINERAS".
 */
@Entity
public class Gasolineras {

    @Id
    private Long gas_id;
    private String nombre_gas;
    private String coordenadas;
    private String direccion;
    private Boolean visited;
    private String fecha;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Gasolineras() {
    }

    public Gasolineras(Long gas_id) {
        this.gas_id = gas_id;
    }

    @Generated
    public Gasolineras(Long gas_id, String nombre_gas, String coordenadas, String direccion, Boolean visited, String fecha) {
        this.gas_id = gas_id;
        this.nombre_gas = nombre_gas;
        this.coordenadas = coordenadas;
        this.direccion = direccion;
        this.visited = visited;
        this.fecha = fecha;
    }

    public Long getGas_id() {
        return gas_id;
    }

    public void setGas_id(Long gas_id) {
        this.gas_id = gas_id;
    }

    public String getNombre_gas() {
        return nombre_gas;
    }

    public void setNombre_gas(String nombre_gas) {
        this.nombre_gas = nombre_gas;
    }

    public String getCoordenadas() {
        return coordenadas;
    }

    public void setCoordenadas(String coordenadas) {
        this.coordenadas = coordenadas;
    }

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public Boolean getVisited() {
        return visited;
    }

    public void setVisited(Boolean visited) {
        this.visited = visited;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
