package com.hics.g500.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "OPCIONES".
 */
@Entity
public class Opciones {
    private Long pregunta_id;
    private Long encuenta_id;

    @Id
    private Long opcion_id;
    private String opcion_contenido;
    private String opcion_url;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Opciones() {
    }

    public Opciones(Long opcion_id) {
        this.opcion_id = opcion_id;
    }

    @Generated
    public Opciones(Long pregunta_id, Long encuenta_id, Long opcion_id, String opcion_contenido, String opcion_url) {
        this.pregunta_id = pregunta_id;
        this.encuenta_id = encuenta_id;
        this.opcion_id = opcion_id;
        this.opcion_contenido = opcion_contenido;
        this.opcion_url = opcion_url;
    }

    public Long getPregunta_id() {
        return pregunta_id;
    }

    public void setPregunta_id(Long pregunta_id) {
        this.pregunta_id = pregunta_id;
    }

    public Long getEncuenta_id() {
        return encuenta_id;
    }

    public void setEncuenta_id(Long encuenta_id) {
        this.encuenta_id = encuenta_id;
    }

    public Long getOpcion_id() {
        return opcion_id;
    }

    public void setOpcion_id(Long opcion_id) {
        this.opcion_id = opcion_id;
    }

    public String getOpcion_contenido() {
        return opcion_contenido;
    }

    public void setOpcion_contenido(String opcion_contenido) {
        this.opcion_contenido = opcion_contenido;
    }

    public String getOpcion_url() {
        return opcion_url;
    }

    public void setOpcion_url(String opcion_url) {
        this.opcion_url = opcion_url;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return this.getOpcion_contenido();
    }
    // KEEP METHODS END

}
