package com.hics.g500.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "OPCIONES".
 */
@Entity
public class Opciones {

    @Id(autoincrement = true)
    private Long id;
    private Integer pregunta_id;
    private Integer encuenta_id;
    private Integer opcion_id;
    private String opcion_contenido;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Opciones() {
    }

    public Opciones(Long id) {
        this.id = id;
    }

    @Generated
    public Opciones(Long id, Integer pregunta_id, Integer encuenta_id, Integer opcion_id, String opcion_contenido) {
        this.id = id;
        this.pregunta_id = pregunta_id;
        this.encuenta_id = encuenta_id;
        this.opcion_id = opcion_id;
        this.opcion_contenido = opcion_contenido;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPregunta_id() {
        return pregunta_id;
    }

    public void setPregunta_id(Integer pregunta_id) {
        this.pregunta_id = pregunta_id;
    }

    public Integer getEncuenta_id() {
        return encuenta_id;
    }

    public void setEncuenta_id(Integer encuenta_id) {
        this.encuenta_id = encuenta_id;
    }

    public Integer getOpcion_id() {
        return opcion_id;
    }

    public void setOpcion_id(Integer opcion_id) {
        this.opcion_id = opcion_id;
    }

    public String getOpcion_contenido() {
        return opcion_contenido;
    }

    public void setOpcion_contenido(String opcion_contenido) {
        this.opcion_contenido = opcion_contenido;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
