package com.hics.g500.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "RESPUESTA_DETALLE".
 */
@Entity
public class RespuestaDetalle {

    @Id(autoincrement = true)
    private Long id;
    private Long pregunta_id;
    private Integer tipo_id;
    private Integer respuestacodigo;
    private String respuestatexto;
    private Long id_parent;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public RespuestaDetalle() {
    }

    public RespuestaDetalle(Long id) {
        this.id = id;
    }

    @Generated
    public RespuestaDetalle(Long id, Long pregunta_id, Integer tipo_id, Integer respuestacodigo, String respuestatexto, Long id_parent) {
        this.id = id;
        this.pregunta_id = pregunta_id;
        this.tipo_id = tipo_id;
        this.respuestacodigo = respuestacodigo;
        this.respuestatexto = respuestatexto;
        this.id_parent = id_parent;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPregunta_id() {
        return pregunta_id;
    }

    public void setPregunta_id(Long pregunta_id) {
        this.pregunta_id = pregunta_id;
    }

    public Integer getTipo_id() {
        return tipo_id;
    }

    public void setTipo_id(Integer tipo_id) {
        this.tipo_id = tipo_id;
    }

    public Integer getRespuestacodigo() {
        return respuestacodigo;
    }

    public void setRespuestacodigo(Integer respuestacodigo) {
        this.respuestacodigo = respuestacodigo;
    }

    public String getRespuestatexto() {
        return respuestatexto;
    }

    public void setRespuestatexto(String respuestatexto) {
        this.respuestatexto = respuestatexto;
    }

    public Long getId_parent() {
        return id_parent;
    }

    public void setId_parent(Long id_parent) {
        this.id_parent = id_parent;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
